### ISSUE TITLE
profiler buttons are not displayed for non-admin user

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/odoo-profiler#20]
There are many cases where a performance issue is related just with a process using a particular user.
But the buttons are not displayed for a user different to `admin`

**Comment by hugho-ad** [comment]
@moylop260 this can be done by setting the group `Profiling capability` in Settings/users
![image](https://user-images.githubusercontent.com/10233975/27394034-6bda4c22-5670-11e7-9773-2416c082bfef.png)
